apiVersion: k8s.sandstorm.de/v1alpha1
kind: OneContainerOnePort
metadata:
  namespace: myvendor-awesomeneosproject-staging
  name: AwesomeNeosProject
spec:
  appName: AwesomeNeosProject
  description: 'Sample Neos Deployment in the Rancher Cluster.'

  hostNames:
    myvendor-awesomeneosproject-staging.cloud.sandstorm.de: []

  node: worker1
  image: docker-hub.sandstorm.de/infrastructure/neos-on-docker-kickstart:master

  port: 8080
  # Set to false when a real DNS entry for staging/production exists
  stagingCertificates: false

  env:
    NGINX_PORT: 8080
    NGINX_HOST: '0.0.0.0'
    FLOW_CONTEXT: 'Production/Kubernetes'
  envFromConfigMaps:
    - db
  envFromSecrets:
    - db

  redis: transient

  volumes:
    - name: persistent
      mountPath: /app/Data/Persistent

  sso:
    enabled: false

  stopped: false
