apiVersion: k8s.sandstorm.de/v1alpha1
kind: OneContainerOnePort
metadata:
  namespace: projectx
  name: app
spec:
  appName: projectx
  description: 'Sample Neos Deployment in the Rancher Cluster.'

  hostNames:
    neos-kickstart.cloud.sandstorm.de: []

  worker: worker1
  image: docker-hub.sandstorm.de/infrastructure/neos-on-docker-kickstart:master

  port: 80
  stagingCertificates: false

  env:
    NGINX_PORT: 80
    NGINX_HOST: '0.0.0.0'
  envFromConfigMaps:
    - db
  envFromSecrets:
    - db

  volumes:
    - name: persistent
      mountPath: /app/Data/Persistent

  sso:
    enabled: false

  stopped: false
