stages:
  - compile_resources
  - build
  - test
  - deploy

include:
  - local: ci/common.gitlab-ci.yml
  - local: ci/tests.gitlab-ci.yml
  - local: ci/staging.gitlab-ci.yml
  # include for production deployment
  #- local: ci/production.gitlab-ci.yml
