##################################################
##### DEVELOPMENT ENVIRONMENT           ##########
##################################################

# Public ports:
#  - 8081 -> Neos
#  - 13306 -> maria db (used for Neos)

version: '3.5'
services:
  #####
  # Neos CMS (php-fpm)
  neos:
    build:
      context: .
      dockerfile: ./deployment/local-dev/neos/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      FLOW_CONTEXT: 'Development/Docker'
      COMPOSER_CACHE_DIR: '/composer_cache'
      # DB connection
      DB_NEOS_HOST: 'maria-db'
      DB_NEOS_PORT: 3306
      DB_NEOS_PASSWORD: 'neos'
      DB_NEOS_USER: 'neos'
      DB_NEOS_DATABASE: 'neos'
      DB_NEOS_DATABASE_E2ETEST: 'neos_e2etest'
      # auto site import
      SITE_IMPORT_PACKAGE_KEY: 'MyVendor.AwesomeNeosProject'
      # auto creation of admin user for Neos backend
      ADMIN_USERNAME: 'admin'
      ADMIN_PASSWORD: 'password'
      PLAYWRIGHT_API_URL: 'http://host.docker.internal:3000'
      SYSTEM_UNDER_TEST_URL_FOR_PLAYWRIGHT: 'http://127.0.0.1:9090'
      # used for flushing caches before scenarios
      E2E_FLOW_CONTEXT: 'Development/Docker/Behat'
      REDIS_HOST: 'redis-cache'
      REDIS_PORT: 6379
    volumes:
      - ./app/composer.json:/app/composer.json:cached
      - ./app/composer.lock:/app/composer.lock:cached
      - ./app/DistributionPackages/:/app/DistributionPackages/:cached
      - ./app/Build/Behat/:/app/Build/Behat/:cached
      - ./app/ContentDump/:/app/ContentDump/:cached
      # Content is writable to enable content dumps from inside the container
      - ./app/DistributionPackages/MyVendor.AwesomeNeosProject/Resources/Private/Content:/app/DistributionPackages/MyVendor.AwesomeNeosProject/Resources/Private/Content/:cached
      - ./app/DistributionPackages/MyVendor.AwesomeNeosProject/Migrations/:/app/DistributionPackages/MyVendor.AwesomeNeosProject/Migrations/:cached
      # mount all packages - enable VirtioFS in your docker host settings or comment out this line
      #- ./app/Packages/:/app/Packages/:cached
      - ./app/Configuration/:/app/Configuration/:cached
      # Explcitly set up Composer cache for faster fetching of packages
      - ./tmp/composer_cache:/composer_cache:cached
    networks:
      - awesomeneosproject
    ports:
      - 8081:8081
      - 9090:9090
    depends_on:
      - maria-db
      - redis-cache

  #####
  # assets build (watcher)
  neos-assets:
    build:
      context: .
      dockerfile: ./deployment/local-dev/neos-assets/Dockerfile
    volumes:
      # everything is readonly except the "Public" folder (which contains the build results);
      - ./app/DistributionPackages/MyVendor.AwesomeNeosProject/Resources/Private:/app/src/Private/:cached
      - ./app/DistributionPackages/MyVendor.AwesomeNeosProject/Resources/Public:/app/src/Public/:cached
      # The node modules folder is an extra (writable) volume to not be part of the outer volume.
      # This is an optimization to NOT include the huge node_modules in the synchronization between host and guest
      # NOTE: for this to work, the node_modules folder as mount target must EXIST when being mounted; so it is checked into git (with an empty placeholder file)
      - neos-assets-node-modules:/app/src/Private/node_modules
      # Explicitly set up Yarn cache for faster fetching of packages
      - ./tmp/.yarn-cache/:/app/.yarn-cache/:cached
    networks:
      - awesomeneosproject

  #####
  # Maria DB
  maria-db:
    image: mariadb:10.3
    ports:
      - 13306:3306
    networks:
      - awesomeneosproject
    environment:
      MYSQL_ROOT_PASSWORD: neos
      MYSQL_DATABASE: neos
      MYSQL_USER: neos
      MYSQL_PASSWORD: neos
      DATABASE_E2ETEST: neos_e2etest
    # use Unicode encoding as default!
    volumes:
      - ./deployment/local-dev/maria-db/createTestingDB.sh:/createTestingDB.sh:cached
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  #####
  # Mailhog (local smtp)
  mailhog:
    image: mailhog/mailhog:latest
    hostname: mailhog
    ports:
      - '8025:8025'
    networks:
      - awesomeneosproject

  redis-cache:
    image: redis:6.2.2
    ports:
      - 16379:6379
    networks:
      - awesomeneosproject

volumes:
  neos-assets-node-modules:

networks:
  # we need to use a custom network here to ensure that all services see each other; and that during prerendering, we can connect to this network (to reach the service facade)
  awesomeneosproject:
    name: awesomeneosproject
