Neos:
  ContentRepository:
    contentDimensions:
      language:
        label: 'Language'
        icon: 'icon-language'
        default: 'de'
        defaultPreset: 'de'
        presets:
          'de':
            label: 'de'
            values: [ 'de' ]
            uriSegment: 'de'
  Flow:
    mvc:
      routes:
        'Neos.Neos':
          variables:
            # We prefer URLs without the ".html" suffix
            defaultUriSuffix: ''
  Neos:
    eventLog:
      enabled: true
    navigateComponent:
      nodeTree:
        loadingDepth: 1
      structureTree:
        loadingDepth: 2
    fusion:
      autoInclude:
        Sandstorm.ProjectX: true
    Ui:
      frontendConfiguration:
        defaultInlineEditor: 'ckeditor5'
        hotkeys: ~
