# local development setup (docker)

Neos:
  Flow:
    persistence:
      # https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html
      backendOptions:
        driver: 'pdo_mysql'
        charset: 'utf8'
        host: '%env:DB_NEOS_HOST%'
        port: '%env:DB_NEOS_PORT%'
        password: '%env:DB_NEOS_PASSWORD%'
        user: '%env:DB_NEOS_USER%'
        dbname: '%env:DB_NEOS_DATABASE%'

  Imagine:
    driver: 'Vips'
    enabledDrivers:
      Vips: true
      Gd: true
      Imagick: true

  Media:
    image:
      defaultOptions:
        # The Vips driver does not support interlace
        interlace: ~

# The propType-validation is enabled via settings.
# By default this setting is enabled for Development and Testing context but not enabled for Production.
PackageFactory:
  AtomicFusion:
    PropTypes:
      enable: true