# NOTE: this file is executed from the ROOT DIRECTORY of the project, i.e. "../"
FROM sandstormmedia/neos-base:1.0.4
ADD deployment/local-dev/neos/entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
