Neos:
  Flow:
    persistence:
      backendOptions:
        driver: 'pdo_mysql'
        charset: 'utf8'
        host: mariadb
        port: 3306
        password: '%env:MYSQL_PASSWORD%'
        user: '%env:MYSQL_USER%'
        dbname: '%env:MYSQL_DATABASE%'
