Flow_Mvc_Routing_Route:
  backend: 'Neos\Cache\Backend\RedisBackend'
  backendOptions:
    hostname: '%env:REDIS_HOST%'
    port: 6379
    # starting with database 2 here, since 0 and 1 are used and flushed by
    # the core unit tests and should not be used if possible.
    database: 2
    defaultLifetime: 0

Flow_Mvc_Routing_Resolve:
  backend: 'Neos\Cache\Backend\RedisBackend'
  backendOptions:
    hostname: '%env:REDIS_HOST%'
    port: 6379
    database: 2
    defaultLifetime: 0

Neos_Fusion_Content:
  backend: 'Sandstorm\OptimizedRedisCacheBackend\OptimizedRedisCacheBackend'
  backendOptions:
    hostname: '%env:REDIS_HOST%'
    port: 6379
    database: 2
    defaultLifetime: 0

Flow_Session_MetaData:
  backend: 'Neos\Cache\Backend\RedisBackend'
  backendOptions:
    hostname: '%env:REDIS_HOST%'
    port: 6379
    database: 2
    defaultLifetime: 0

Flow_Session_Storage:
  backend: 'Neos\Cache\Backend\RedisBackend'
  backendOptions:
    hostname: '%env:REDIS_HOST%'
    port: 6379
    database: 2
    defaultLifetime: 0

Neos_Media_ImageSize:
  backend: 'Neos\Cache\Backend\RedisBackend'
  backendOptions:
    hostname: '%env:REDIS_HOST%'
    port: 6379
    database: 2
    defaultLifetime: 0
