# Comment in when using simple search from flowpack

# we want a different search index for local dev and local e2e-tests
#Flowpack\SimpleSearch\Search\SqLiteQueryBuilder:
#  properties:
#    indexClient:
#      object:
#        factoryObjectName: Flowpack\SimpleSearch\Factory\IndexFactory
#        factoryMethodName: create
#        arguments:
#          1:
#            # this is the e2e-test search index name
#            value: 'Neos_CR_Behat'
