<?php

namespace MyVendor\AwesomeNeosProject\Command;

use Neos\ContentRepository\Domain\Model\NodeInterface;
use Neos\ContentRepository\Domain\NodeType\NodeTypeConstraints;
use Neos\ContentRepository\Domain\Service\ContextFactoryInterface;
use Neos\Flow\Annotations as Flow;
use Neos\Flow\Cli\CommandController;
use Sandstorm\E2ETestTools\StepGenerator\NodeTable;

class StepGeneratorCommandController extends CommandController
{
    /**
     * @Flow\Inject
     * @var ContextFactoryInterface
     */
    protected $contextFactory;

    public function homepageCommand()
    {
        $nodeTable = new NodeTable([]);
        $siteNode = $this->getSiteNode();

        $nodeTable->addParents($siteNode);
        $nodeTable->addNode($siteNode);
        $nodeTable->addNodesUnderneathExcludingAutoGeneratedChildNodes($siteNode, '!Neos.Neos:Document'); // we recurse into the content of the homepage
        $nodeTable->addNodesUnderneathExcludingAutoGeneratedChildNodes($siteNode, 'Neos.Neos:Document,!MyVendor.AwesomeNeosProject:Document.Blog'); // we render the remaining document nodes so we can have a menu rendered (but without content)

        $nodeTable->print();
    }

    public function notFoundPageCommand()
    {
        $nodeTable = new NodeTable([]);
        $siteNode = $this->getSiteNode();

        $nodeTable->addParents($siteNode);
        $nodeTable->addNode($siteNode);
        $filter = new NodeTypeConstraints(false, ['MyVendor.AwesomeNeosProject:Document.NotFoundPage']);
        $notFoundPageNodes = $siteNode->findChildNodes($filter);
        foreach ($notFoundPageNodes as $notFoundPageNode) {
            $nodeTable->addNode($notFoundPageNode);
            $nodeTable->addNodesUnderneathExcludingAutoGeneratedChildNodes($notFoundPageNode, '!Neos.Neos:Document'); // 404 page content
        }

        $nodeTable->print();
    }

    /**
     * @return NodeInterface
     */
    public function getSiteNode(): NodeInterface
    {
        $context = $this->contextFactory->create([
            'workspaceName' => 'live',
            'invisibleContentShown' => true,
            'dimensions' => [
            ],
            'targetDimensions' => [
            ]
        ]);
        return $context->getCurrentSiteNode();
    }
}
